src/Entity/Candidate.php
<?php

namespace App\Entity;

use App\Repository\CandidateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidateRepository::class)]
class Candidate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 40)]
    private $lastName;

    #[ORM\Column(type: 'string', length: 30)]
    private $firstName;

    #[ORM\Column(type: 'string', length: 60)]
    private $email;

    #[ORM\Column(type: 'string', length: 25)]
    private $phone;

    #[ORM\OneToMany(mappedBy: 'candidate', targetEntity: Result::class)]
    private $results;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'candidates')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $deleteDate;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $cvFileName;

    #[ORM\Column(type: 'datetime')]
    private $lastUpdate;

    public function __construct()
    {
        $this->results = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection<int, Result>
     */
    public function getResults(): Collection
    {
        return $this->results;
    }

    public function addResult(Result $result): self
    {
        if (!$this->results->contains($result)) {
            $this->results[] = $result;
            $result->setCandidate($this);
        }

        return $this;
    }

    public function removeResult(Result $result): self
    {
        if ($this->results->removeElement($result)) {
            // set the owning side to null (unless already changed)
            if ($result->getCandidate() === $this) {
                $result->setCandidate(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDeleteDate(): ?\DateTimeInterface
    {
        return $this->deleteDate;
    }

    public function setDeleteDate(?\DateTimeInterface $deleteDate): self
    {
        $this->deleteDate = $deleteDate;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getLastName() . ' ' . $this->getFirstName();
    }

    public function getCvFileName(): ?string
    {
        return $this->cvFileName;
    }

    public function setCvFileName(?string $cvFileName): self
    {
        $this->cvFileName = $cvFileName;

        return $this;
    }

    public function getLastUpdate(): ?\DateTimeInterface
    {
        return $this->lastUpdate;
    }

    public function setLastUpdate(\DateTimeInterface $lastUpdate): self
    {
        $this->lastUpdate = $lastUpdate;

        return $this;
    }
}

src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuestionRepository::class)]
class Question
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $question;

    #[ORM\ManyToOne(targetEntity: Survey::class, inversedBy: 'questions')]
    #[ORM\JoinColumn(nullable: false)]
    private $Survey;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $deleteDate;

    #[ORM\OneToMany(mappedBy: 'question', targetEntity: Answer::class)]
    private $answers;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $imgFileName;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getSurvey(): ?Survey
    {
        return $this->Survey;
    }

    public function setSurvey(?Survey $Survey): self
    {
        $this->Survey = $Survey;

        return $this;
    }

    public function getDeleteDate(): ?\DateTimeInterface
    {
        return $this->deleteDate;
    }

    public function setDeleteDate(?\DateTimeInterface $deleteDate): self
    {
        $this->deleteDate = $deleteDate;

        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    public function getImgFileName(): ?string
    {
        return $this->imgFileName;
    }

    public function setImgFileName(?string $imgFileName): self
    {
        $this->imgFileName = $imgFileName;

        return $this;
    }
}

src/Entity/VisibleCourse.php
<?php

namespace App\Entity;

use App\Repository\VisibleCourseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VisibleCourseRepository::class)]
class VisibleCourse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'visibleCourses')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\ManyToOne(targetEntity: Course::class, inversedBy: 'visibleCourses')]
    #[ORM\JoinColumn(nullable: false)]
    private $Course;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCourse(): ?Course
    {
        return $this->Course;
    }

    public function setCourse(?Course $Course): self
    {
        $this->Course = $Course;

        return $this;
    }
    public function __toString(): string
    {
        return $this->getUser()->getLastName() . ' ' . $this->getUser()->getFirstName() ;
    }


}

src/Form/CandidateType.php
<?php

namespace App\Form;

use App\Entity\Candidate;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;

class CandidateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('lastName', TextType::class, [
                'label' => 'Nom',
                'attr' => ['maxlength' => 40],
                'constraints' => new Length([
                    'max' => 40,
                    'maxMessage' => '{{ limit }} caractères maximum autorisés',
                ])
            ])
            ->add('firstName', TextType::class, [
                'label' => 'Prénom',
                'attr' => ['maxlength' => 30],
                'constraints' => new Length([
                    'max' => 30,
                    'maxMessage' => '{{ limit }} caractères maximum autorisés',
                ])
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email',
                'attr' => ['maxlength' => 60],
                'constraints' => new Length([
                    'max' => 60,
                    'maxMessage' => '{{ limit }} caractères maximum autorisés',
                ])
            ])
            ->add('phone', TelType::class, [
                'label' => 'Téléphone',
                'attr' => ['maxlength' => 25],
                'constraints' => new Length([
                    'max' => 25,
                    'maxMessage' => '{{ limit }} caractères maximum autorisés',
                ])
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Candidate::class,
        ]);
    }
}

src/Controller/CandidateController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Candidate;
use App\Form\CandidateType;
use App\Repository\CandidateRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

/**
 * @IsGranted("ROLE_CENTER")
 */
#[Route('/candidate')]
class CandidateController extends AbstractController
{
    #[Route('/', name: 'app_candidate_index', methods: ['GET'])]
    public function index(CandidateRepository $candidateRepository): Response
    {
        $user = $this->getUser();
        // Si administrateur afficher tous les candidats
        if ($this->isGranted("ROLE_ADMIN")) {
            return $this->render('candidate/index.html.twig', [
                'candidates' => $candidateRepository->findAll(),
            ]);
        }
        // Sinon n'afficher que les candidats rattachés au centre et non supprimés.
        return $this->render('candidate/index.html.twig', [
            'candidates' => $candidateRepository->findBy([
                'user' => $user,
                'deleteDate' => null
            ]),
        ]);
    }

    #[Route('/oldEntries', name: 'app_candidate_old_entries', methods: ['GET'])]
    public function indexOldEntries(CandidateRepository $candidateRepository): Response
    {
        $user = $this->getUser();
        // Si administrateur afficher tous les candidats
        if ($this->isGranted("ROLE_ADMIN")) {
            return $this->render('candidate/index.html.twig', [
                'candidates' => $candidateRepository->findAll(),
            ]);
        }

        // Sinon n'afficher que les candidats rattachés au centre et non supprimés.
        return $this->render('candidate/indexOldEntries.html.twig', [
            'candidates' => $candidateRepository->findBy([
                'user' => $user,
                'deleteDate' => null
            ]),
        ]);
    }


    #[Route('/new', name: 'app_candidate_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CandidateRepository $candidateRepository): Response
    {
        $candidate = new Candidate();
        $form = $this->createForm(CandidateType::class, $candidate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Affecter le nouveau candidat à l'utilisateur actuel.
            // TODO ajouter une fonction admin pour affecter un candidat a un centre.
            $candidate->setUser($this->getUser());
            $candidate->setLastUpdate(new DateTime());
            $candidateRepository->add($candidate, true);
            $this->addFlash('success', 'Candidat : ' . $candidate->getFirstName() . ' ' . $candidate->getLastName() . ' ajouté !');
            return $this->redirectToRoute('app_candidate_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('candidate/new.html.twig', [
            'candidate' => $candidate,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_candidate_show', methods: ['GET'])]
    public function show(Candidate $candidate): Response
    {
        // Si l'utilisateur n'est pas administrateur, gérer l'accès.
        if (!$this->isGranted("ROLE_ADMIN")) {
            // Si la fiche du candidat n'appartient pas au centre ou que la fiche a été supprimée générer une erreur 403.
            if ($this->getUser() !== $candidate->getUser() | $candidate->getDeleteDate() !== null)
                throw new AccessDeniedHttpException();
        }
        return $this->render('candidate/show.html.twig', [
            'candidate' => $candidate,
        ]);
    }

    #[
        Route('/{id}/edit', name: 'app_candidate_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Candidate $candidate, CandidateRepository $candidateRepository): Response
    {
        // Si l'utilisateur n'est pas administrateur, gérer l'accès.
        if (!$this->isGranted("ROLE_ADMIN")) {
            // Si la fiche du candidat n'appartient pas au centre ou que la fiche a été supprimée générer une erreur 403.
            if ($candidate->getUser() !== $this->getUser() | $candidate->getDeleteDate() !== null)
                throw new AccessDeniedHttpException();
        }
        $form = $this->createForm(CandidateType::class, $candidate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $candidateRepository->add($candidate, true);
            $this->addFlash('success', 'Fiche de ' . $candidate->getFirstName() . ' ' . $candidate->getLastName() . ' modifiée !');

            return $this->redirectToRoute('app_candidate_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('candidate/edit.html.twig', [
            'candidate' => $candidate,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_candidate_delete', methods: ['POST'])]
    public function delete(Request $request, Candidate $candidate, CandidateRepository $candidateRepository): Response
    {
        // Si l'utilisateur n'est pas administrateur, gérer l'accès.
        if (!$this->isGranted("ROLE_ADMIN")) {
            // Si la fiche du candidat n'appartient pas au centre ou que la fiche a déjà été supprimée générer une erreur 403.
            if ($this->getUser() !== $candidate->getUser() | $candidate->getDeleteDate() !== null)
                throw new AccessDeniedHttpException();
        }
        if ($this->isCsrfTokenValid('delete' . $candidate->getId(), $request->request->get('_token'))) {
            $candidateRepository->softDelete($candidate, true);
        }
        $this->addFlash('alert', 'Fiche de ' . $candidate->getFirstName() . ' ' . $candidate->getLastName() . ' supprimée !');

        return $this->redirectToRoute('app_candidate_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/candidate/_delete_form.html.twig
<form method="post" action="{{ path('app_candidate_delete', {'id': candidate.id}) }}"
      onsubmit="return confirm('Enes vous sur de vouloir supprimer la fiche de {{ candidate.lastName }} {{ candidate.firstName }} ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidate.id) }}">
    <button title="Supprimer" class="btn btn-danger mx-2"><i class="fa-solid fa-trash-can"></i></button>
</form>

templates/candidate/_form.html.twig
<div class="form">
    {{ form_start(form) }}
    <div class="row d-flex justify-content-center">
        <div class="col-12 col-sm-5">
            {{ form_row(form.lastName) }}
        </div>
        <div class="col-12 col-sm-3">
            {{ form_row(form.firstName) }}
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-12 col-sm-5">
            {{ form_row(form.email) }}
        </div>

        <div class="col-12 col-sm-3">
            {{ form_row(form.phone) }}
        </div>

    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-12 col-sm-8 d-flex justify-content-end">
            <a class="btn btn-info mx-2" title="Retour"
               href="{{ path('app_candidate_index') }}"><i class="fa-solid fa-backward"></i></a>
            <button title="Valider" class="btn btn-success mx-2"><i class="fa-solid fa-check"></i></button>
        </div>
    </div>
    {{ form_end(form) }}
</div>

templates/candidate/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier fiche candidat{% endblock %}

{% block body %}
<section>
    <h1 class="h1 mb-3 font-weight-normal text-center">Modifier fiche candidat</h1>

    {{ include('candidate/_form.html.twig') }}

</section>
{% endblock %}

templates/candidate/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des candidats{% endblock %}

{% block body %}
    <h1 class="h1 mb-3 font-weight-normal text-center">Liste des candidats</h1>

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Téléphone</th>
        </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
            <tr onclick="location.href='{{ path('app_candidate_show', {'id': candidate.id}) }}'">
                <td>{{ candidate.lastName }}</td>
                <td>{{ candidate.firstName }}</td>
                <td>{{ candidate.email }}</td>
                <td>{{ candidate.phone }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Pas de candidats</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex justify-content-end">
        <a class="btn btn-primary" href="{{ path('app_candidate_new') }}">Créer une fiche candidat</a>
    </div>
{% endblock %}

templates/candidate/indexOldEntries.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des candidats{% endblock %}

{% block body %}
    <h1 class="h1 mb-3 font-weight-normal text-center">Liste des candidats</h1>
    <p class="text-center">Fonction en cours de développement.</p>
    <div class="d-flex justify-content-end my-2">
        <a class="btn btn-primary mx-2" href="{{ path('app_candidate_index') }}">Retour liste générale</a>
        <a class="btn btn-primary mx-2" href="{{ path('app_candidate_new') }}">Créer une fiche candidat</a>
    </div>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Téléphone</th>
        </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
            <tr onclick="location.href='{{ path('app_candidate_show', {'id': candidate.id}) }}'">
                <td>{{ candidate.lastName }}</td>
                <td>{{ candidate.firstName }}</td>
                <td>{{ candidate.email }}</td>
                <td>{{ candidate.phone }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Pas de candidats</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/candidate/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Candidate{% endblock %}

{% block body %}
    <section>
        <h1 class="h3 mb-3 font-weight-normal text-center">Ajouter un candidat</h1>

        {{ include('candidate/_form.html.twig') }}
    </section>

{% endblock %}

templates/candidate/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche {{ candidate }}{% endblock %}

{% block body %}
    <section id="candidateDetail">
        <h1 class="h1 mb-3 font-weight-normal text-center">Fiche de {{ candidate }}</h1>

        <table class="table">
            <tbody>
            <tr>
                <th>Nom de famille</th>
                <td>{{ candidate.lastName }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ candidate.firstName }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td><a href="mailto:{{ candidate.email }}">{{ candidate.email }}</a></td>
            </tr>
            <tr>
                <th>Téléphone</th>
                <td>{{ candidate.phone }}</td>
            </tr>
            {% if candidate.cvFileName %}
                <th>CV du candidat</th>
                <td>
                    <a href="{{ asset('./cv_files/'~ candidate.cvFileName) }}">
                        Lien <i class="fa-solid fa-file-pdf" style="font-size: 20px"></i></a>
                </td>
            {% endif %}
            </tbody>
        </table>

        <div class="row d-flex justify-content-end mb-3">
            <div class="col-12 d-flex justify-content-end">
                <a class="btn btn-primary mx-2" title="Retour"
                   href="{{ path('app_candidate_index') }}"><i class="fa-solid fa-delete-left"></i></a>
                <a class="btn btn-info mx-2" title="Modifier"
                   href="{{ path('app_candidate_edit', {'id': candidate.id}) }}"><i
                            class="fa-solid fa-user-pen"></i></a>
                {{ include('candidate/_delete_form.html.twig') }}
            </div>
        </div>

        <h2 class="h2 mb-3 font-weight-normal text-center">Résultats</h2>


        <div class="flex mb-3">
            {% for result in candidate.results %}
                <div class="card">
                    <div class="card-header">
                        Formation : {{ result.survey.course }}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ result.survey }}</h5>
                        {% if result.score %}
                            {% if result.isCheater %}
                                <p class="card-text" style="color: red">Score : {{ result.finalScore }}
                                    % </p>
                            {% else %}
                                <p class="card-text" style="color: green">Score : {{ result.finalScore }}
                                    % </p>
                            {% endif %}
                        {% else %}
                            <p class="card-text">Test non réalisé</p>
                        {% endif %}
                        <div class="d-flex justify-content-end">
                            <a href="{{ path('app_result_show', {'id': result.id}) }}"
                               class="btn btn-primary"><i class="fa-solid fa-magnifying-glass"></i></a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>

    </section>
{% endblock %}